# シンプルなCloudflare Workers設定
name = "my-project-template-api"
main = "src/worker.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# プレビュー環境
[env.preview]
name = "my-project-template-api-preview"
keep_vars = true  # GUI設定の環境変数を保護

[env.preview.vars]
NODE_ENV = "preview"
# FRONTEND_URLはCloudflare Dashboardまたはwrangler secretで設定

# 本番環境
[env.production] 
name = "my-project-template-api-production"
keep_vars = true  # GUI設定の環境変数を保護

[env.production.vars]
NODE_ENV = "production"
# FRONTEND_URLはCloudflare Dashboardまたはwrangler secretで設定

# ローカル環境変数（.dev.varsで設定）
[vars]
NODE_ENV = "development"