services:
  frontend:
    build:
      context: ../../
      dockerfile: ./infra/docker/Dockerfile.frontend
    ports:
      - '3000:3000'
    volumes:
      - ../../apps/frontend:/app/apps/frontend
      - ../../packages:/app/packages
      - ../../tools:/app/tools
      - ../../contracts:/app/contracts
      - /app/node_modules
      - /app/apps/frontend/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    command: ['pnpm', '--filter', '@template/frontend', 'dev']

  backend:
    build:
      context: ../../
      dockerfile: ./infra/docker/Dockerfile.backend
    ports:
      - '8000:8000'
    volumes:
      - ../../apps/backend:/app/apps/backend
      - ../../packages:/app/packages
      - ../../tools:/app/tools
      - ../../contracts:/app/contracts
      - /app/node_modules
      - /app/apps/backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
    networks:
      - app-network
    command: ['pnpm', '--filter', '@template/backend', 'dev']

networks:
  app-network:
    driver: bridge
